### ISSUE TITLE
 AttributeError: 'NoteCreator' object has no attribute 'result'

### ISSUE THREAD

**Issue by MInner** [sickmartian/quick_simplenote#23]
Ubuntu 14.04, Sublime 3, fresh install

```
QuickSimplenote: Autostarting
QuickSimplenote: Creating note
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "~/.config/sublime-text-3/Packages/QuickSimplenote/operations.py", line 46, in run
    operation_result = self.simplenote_instance.add_note('')
AttributeError: 'NoneType' object has no attribute 'add_note'

QuickSimplenote: Sync ommited 1496170619.597326
Package Control: Skipping automatic upgrade, last run at 2017-05-30 11:52:59, next run at 2017-05-30 12:52:59 or after
Traceback (most recent call last):
  File "~/.config/sublime-text-3/Packages/QuickSimplenote/quick_simplenote.py", line 234, in check_operations
    self.current_operation.join()
  File "~/.config/sublime-text-3/Packages/QuickSimplenote/operations.py", line 22, in join
    result = self.get_result()
  File "~/.config/sublime-text-3/Packages/QuickSimplenote/operations.py", line 59, in get_result
    return self.result
AttributeError: 'NoteCreator' object has no attribute 'result'
```

**Comment by sickmartian** [comment]
Hi, is it reliably working now? If not, can you send me the full log?
Also, did you change the credentials before restarting? Were you simultaneously using another simplenote client?
